### ISSUE TITLE
Need to Un-delegate twice to be successful

### ISSUE THREAD

**Issue by sweetpotatoz** [OwnMarket/OwnBlockchain#3]
https://wallet.weown.com/

Tested to do delegate transfer 1000 CHX to a validator, then try to un-delegate it.
The first transaction status is showing successful
Tx hash 48oDLnRQoDynLDFkLFhtUy7buCPjMUEn87oGgwkeBMGy
But from menu panel, it is still showing 1000 delegated, and available balance is not being updated.

I have to do un-delegate for another time
Tx hash 6Gds9Js4T6itWZWDqLRgxFh27tdxML4bQdVXLyaBYepB
showing success again for the delegated and available balance to be updated.

**Comment by anilmujagic** [comment]
You have delegated 1000 CHX stake to address `CHZGqrbsqnrQ2PPiYeQLBtWAF4UKD1xzuj1` twice with following TXs:
- `DkyPWB3Ea5c2DiDwKjCSQqaxgCXNxSgrXiqDKTo1BT1h`
- `F3RzP5Rr8JPr78eTprNe5MgNP3EEtkS9wK9B6kvYeHd`

That's why you had to revoke the stake twice.
